services:
  gin_executor:
    build:
      context: .
      dockerfile: cmd/gin_executor/Dockerfile
    container_name: app_gin_executor
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  grpc_executor:
    build:
      context: .
      dockerfile: cmd/grpc_executor/Dockerfile
    container_name: app_grpc_executor
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq

  grpc_arithmetic:
    build:
      context: .
      dockerfile: cmd/grpc_arithmetic/Dockerfile
    container_name: app_grpc_arithmetic
    ports:
      - "50051:50051"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password