// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: arithmetic.proto

package arithmeticpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Arithmetic_Calculate_FullMethodName = "/arithmeticpb.Arithmetic/Execute"
)

// ArithmeticClient is the client API for Arithmetic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArithmeticClient interface {
	Calculate(ctx context.Context, in *CalculationData, opts ...grpc.CallOption) (*Message, error)
}

type arithmeticClient struct {
	cc grpc.ClientConnInterface
}

func NewArithmeticClient(cc grpc.ClientConnInterface) ArithmeticClient {
	return &arithmeticClient{cc}
}

func (c *arithmeticClient) Calculate(ctx context.Context, in *CalculationData, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, Arithmetic_Calculate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArithmeticServer is the server API for Arithmetic service.
// All implementations must embed UnimplementedArithmeticServer
// for forward compatibility.
type ArithmeticServer interface {
	Calculate(context.Context, *CalculationData) (*Message, error)
	mustEmbedUnimplementedArithmeticServer()
}

// UnimplementedArithmeticServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArithmeticServer struct{}

func (UnimplementedArithmeticServer) Calculate(context.Context, *CalculationData) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedArithmeticServer) mustEmbedUnimplementedArithmeticServer() {}
func (UnimplementedArithmeticServer) testEmbeddedByValue()                    {}

// UnsafeArithmeticServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArithmeticServer will
// result in compilation errors.
type UnsafeArithmeticServer interface {
	mustEmbedUnimplementedArithmeticServer()
}

func RegisterArithmeticServer(s grpc.ServiceRegistrar, srv ArithmeticServer) {
	// If the following call pancis, it indicates UnimplementedArithmeticServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Arithmetic_ServiceDesc, srv)
}

func _Arithmetic_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculationData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArithmeticServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Arithmetic_Calculate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArithmeticServer).Calculate(ctx, req.(*CalculationData))
	}
	return interceptor(ctx, in, info, handler)
}

// Arithmetic_ServiceDesc is the grpc.ServiceDesc for Arithmetic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Arithmetic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arithmeticpb.Arithmetic",
	HandlerType: (*ArithmeticServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _Arithmetic_Calculate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arithmetic.proto",
}
