executor_gin_server:
  address: 0.0.0.0
  port: 8080

executor_grpc_server:
  address: 0.0.0.0
  port: 8081

arithmetic_server:
  address: 0.0.0.0
  port: 50051
  host: grpc_arithmetic

rabbitmq_broker:
  uri: amqp://user:password@rabbitmq:5672/